### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by netflash** [RackHD/terraform-provider-ipam#2]
Hi there,

Could you guys please add some tips on how to build that for those who not familiar with golang ?
I tried to copy Makefile from RackHD/ipam, changed the app name inside of that file to `terraform-provider-ipam` and run `make`
but finally have got
```
...
[INFO]  Project relies on 25 dependencies.
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProviderImpl
--- PASS: TestProviderImpl (0.00s)
PASS
coverage: 2.0% of statements

Ginkgo ran 1 suite in 21.027924158s
Test Suite Passed
# command-line-arguments
./main.go:11: undefined: Provider
make: *** [build-local] Error 2
Makefile:25: recipe for target 'build' failed
make: *** [build] Error 2
```

and maybe the first question should be - what is the state of this - WIP, alpha, beta, prod-ready, etc. ? :-)

**Comment by ekaley** [comment]
https://github.com/RackHD/terraform-provider-ipam/commit/a5dc7b9d1c31407c3f60642f0e50aeb1d968815c

@netflash should help you out.  Please let me know and then I will close this :)

**Comment by netflash** [comment]
Great. 
Thank you.

I was able to build it.
I set my `.terraformrc` file with 
```
providers {
  ipam = "/usr/local/bin/terraform-provider-ipam"
}
```

and now I get this

```
Error configuring: 1 error(s) occurred:

* Incompatible API version with plugin. Plugin version: 3, Ours: 2
```

Basically I understand that I've built it with master version of terraform.
So I went to `$GOPATH/src/github/hashicorp/terraform` and switched that to 0.8.7
`git checkout v0.8.7`
and rebuild the plugin.
It works!!!

`terraform plan` with default file showed me this
```
+ ipam_pool.demo_pool
    name: "POOL_1"

+ ipam_reservation.demo_reservation
    ip:     "<computed>"
    name:   "RESERVATION_1"
    subnet: "${ipam_subnet.demo_subnet.id}"

+ ipam_subnet.demo_subnet
    end:   "192.168.1.20"
    name:  "SUBNET_1"
    pool:  "${ipam_pool.demo_pool.id}"
    start: "192.168.1.10"
```

So last question with building - how can I explicitly set the dependency to specific version ?

**Comment by ekaley** [comment]
@netflash , we wrote this a while ago so there may have been api versions of terraform that have been released since then.  Can definitely look at updating the provider to use this updated api version but for now i will close this due to you getting it built and running.  I will add in the maximum terraform version `0.8.7` into the readme for now

**Comment by ekaley** [comment]
https://github.com/RackHD/terraform-provider-ipam/commit/0075dfbf5a402d8e4e03069d930f2ea3fa534c9f
